import glob
import os
import datetime

from tester.write_output import *
#data_path = input("Please enter data path: ")


###### CAMBIA SOLO QUESTI VALORI!!!!!

num_test = 500
main_folder = "./test"
#######################################



def generate_report(data_path):

    path = "%s/" % data_path
    index = 0
    init_output_file(data_path, num_test)  # INIT FILE

    for filename in glob.glob(os.path.join(path, '*.json')):

        print("-- ANALYZE File : %s" %filename)
        try:

            file_id = filename.replace(data_path, "")
            file_id = filename.replace(".json", "")

            file_info = filename.replace("%scaputure_"%data_path, "")

            file_info = file_info.split("_")
            timeout = file_info[1]
            rand_factor = file_info[3]
            retry = file_info[5]
            res = file_info[6]


            # write line for this filename
            write_test_result(index, res, timeout, rand_factor, retry, file_id, data_path, num_test)
            index += 1
        except Exception:
            print(" THIS DATA WAS GENERATED BY OLD CLIENT - SKIP!")





if __name__ == '__main__':

    for directory in glob.glob('%s/*/'% main_folder):

        print ("- check dir: %s" % directory)
        report_file = "%s/report.txt" % directory
        if os.path.exists(report_file) :
            print("RENAME REPORT in %s" %directory)
            dt = str(datetime.datetime.now())
            rename_report = '%s/report_renamed_' % (directory) + dt + '.txt'
            os.rename(report_file, rename_report)
        generate_report("%s" % (directory))